spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 7001 #注册中心占用7001端口，冒号后面必须要有空格
  
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-client
    
eureka:
  instance:
    hostname: eureka7001.com #冒号后面必须要有空格,eureka服务端的实例名称，来至hosts文件的映射
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #单机版设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/   
---
server: 
  port: 7001 #注册中心占用7001端口，冒号后面必须要有空格
  
spring: 
  profiles: 
  application:
    name: microservicecloud-config-eureka-client
    
eureka:
  instance: test
    hostname: eureka7001.com #冒号后面必须要有空格,eureka服务端的实例名称，来至hosts文件的映射
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #单机版设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/   